export const en = {
  brand: 'HARROW & VALE',
  edition: 'SPECIALTY RETAIL',
  workspace: 'ANALYTICS WORKSPACE',
  title: 'Demand planning dashboard',
  eyebrow: 'DEMAND / INVENTORY ANALYTICS',
  subtitle: 'Stock on hand and forward demand for lines bought from other houses',
  cta: 'Discuss your data',
  tourButton: 'Take a tour',
  productAnalysis: 'Product analysis',
  dataThrough: 'Data through',
  forecast: 'Demand forecast',
  forecastNote: 'Observed sales and probabilistic weekly outlook',
  recommendation: 'Inventory position',
  scenarios: 'Scenario parameters',
  why: 'Demand drivers',
  impact: 'The business impact',
  replay: 'Forecast replay',
  historicalView: 'Historical view',
  latest: 'Latest',
  outcome: 'Outcome at this origin',
  ruleOfThumb: 'Rule of thumb',
  modelOrder: 'Model order',
  horizonNote: 'The planning horizon changes the chart, not the order.',
  explanationMissing: 'The explanation for this forecast is temporarily unavailable.',
  tourSteps: [
    { id: 'selection', title: 'Choose a product', body: 'Switch categories and products to inspect a different demand pattern and inventory position.' },
    { id: 'metrics', title: 'Read the key measures', body: 'The recommendation, cash commitment, current stockout risk and safety stock update for the selected product.' },
    { id: 'forecast', title: 'Explore the forecast', body: 'Compare historical sales with the most likely demand and its uncertainty range. Change the horizon or switch to the data table.' },
    { id: 'replenishment', title: 'Examine replenishment', body: 'See the calculated quantity, latest ordering date and the stock position behind the recommendation.' },
    { id: 'scenarios', title: 'Test a scenario', body: 'Change service level, supplier delay, promotion or available stock to see how the decision responds.' },
    { id: 'drivers', title: 'Trace demand drivers', body: 'Read the explanation and compare the estimated contribution of trend, seasonality and events.' },
    { id: 'replay', title: 'Revisit a past forecast', body: 'Move the timeline to compare an earlier forecast with the demand that followed, and with the order each policy would have placed.' },
    { id: 'impact', title: 'Compare outcomes', body: 'Review fill rate, inventory value, lost margin and imbalance cost against the simple baseline.' },
  ],
};
export type DfpStrings = typeof en;
